---
- name: "Variables"
  hosts: localhost
  tasks:
                                    
    - name: "Installing Apache"
  
    - name: "Creating httpd.conf from template file"

    - name: "Creating virtualost from template file"

    - name: "Creating documentroot for virtualhost"

    - name: "Restarting Apache"

    
